# this doesn't work if there is more than one level of symlinks
ME_PATH=${(%):-%x}
ME_DIR=$(dirname $ME_PATH)
[[ -f $ME_DIR/.zshrc-private ]] && source $ME_DIR/.zshrc-private

# Path to your oh-my-zsh installation.
export ZSH=/Users/$USER/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
export ZSH_THEME="powerlevel9k/powerlevel9k"
export POWERLEVEL9K_MODE='nerdfont-complete'
export POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time time)
export POWERLEVEL9K_STATUS_OK=false
export POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B4'
export #POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0C0'
export POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B6'
export POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{004}╭\uE0B6%{$reset_color%}"
export POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{004}╰─▶ %{$reset_color%}%f%b%k"
export #POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR='%F{004}\u2593\u2592\u2591'
export POWERLEVEL9K_MULTILINE_FIRST_PROMPT_FOREGROUND="red"
export #POWERLEVEL9K_TIME_FORMAT="%D{%I:%M%p \uE868  %a %m/%d/%y}"
export POWERLEVEL9K_TIME_FORMAT="%D{%I:%M%p %a %m/%d/%y}"
export POWERLEVEL9K_PROMPT_ON_NEWLINE=true

export COMMON_PLUGINS=(git colorize gradle vagrant branch colored-man-pages dircycle dirhistory docker docker-compose)

export GEM_HOME=$HOME/gems
export PATH="$PATH:$HOME/bin:$GEM_HOME/bin"
LESS="$LESS -q"
if which colorls; then
	alias ls="colorls --gs"
	alias l="colorls -l --gs"
	alias ll="colorls -l --gs"
fi
alias k=kubectl
function c() {
    [ -n "$1" ] && pygmentize -O style=monokai -f console256 -g $1 | less
}
which colordiff && alias diff=colordiff
